mindspore-lab/mindnlp

- examples/sentiment_classification.py
- mindnlp/modules/encoder/__init__.py
- mindnlp/modules/encoder/cnn_encoder.py
- tests/ut/modules/test_encoder.py
> add CNNEncoder

- mindnlp/dataset/machine_translation/__init__.py
- mindnlp/dataset/machine_translation/multi30k.py
- tests/ut/dataset/test_multi30k.py
> add multi30k process

- mindnlp/utils/download.py
Fixed download “http_get“ download issues
> Fixed download “http_get“ download issues

- mindnlp/dataset/text_classification/__init__.py
- mindnlp/dataset/text_classification/yahooanswers.py
- mindnlp/dataset/text_classification/yelpreviewfull.py
- mindnlp/dataset/text_classification/yelpreviewpolarity.py
- tests/ut/dataset/test_yahooanswers.py
- tests/ut/dataset/test_yelpreviewfull.py
- tests/ut/dataset/test_yelpreviewpolarity.py
Add YelpReviewPolarity YelpReviewFull YahooAnswers
> Add YelpReviewPolarity YelpReviewFull YahooAnswers

- mindnlp/dataset/text_classification/__init__.py
- mindnlp/dataset/text_classification/agnews.py
- mindnlp/dataset/text_classification/amazonreviewfull.py
- mindnlp/dataset/text_classification/amazonreviewpolarity.py
- tests/ut/dataset/test_agnews.py
- tests/ut/dataset/test_amazonreviewfull.py
- tests/ut/dataset/test_amazonreviewpolarity.py
> the process of three datasets

- mindnlp/dataset/machine_translation/__init__.py
- mindnlp/dataset/machine_translation/iwslt2017.py
- mindnlp/dataset/process.py
- tests/ut/dataset/test_iwslt2017.py
看一下这样的写法行不行
如果逻辑相同，调用`mindnlp.utils`的`common_process`
如果遇到特殊的数据集，也可以不进行调用，另外写
> add iwslt2017 process with common process

- mindnlp/dataset/machine_translation/iwslt2016.py
- mindnlp/dataset/machine_translation/iwslt2017.py
- mindnlp/dataset/machine_translation/multi30k.py
- mindnlp/dataset/question_answer/squad1.py
- mindnlp/dataset/question_answer/squad2.py
- mindnlp/dataset/sequence_tagging/conll2000chunking.py
- mindnlp/dataset/sequence_tagging/udpos.py
- mindnlp/dataset/text_classification/agnews.py
- mindnlp/dataset/text_classification/amazonreviewfull.py
- mindnlp/dataset/text_classification/amazonreviewpolarity.py
- mindnlp/dataset/text_classification/cola.py
- mindnlp/dataset/text_classification/dbpedia.py
- mindnlp/dataset/text_classification/imdb.py
- mindnlp/dataset/text_classification/mnli.py
- mindnlp/dataset/text_classification/mrpc.py
- mindnlp/dataset/text_classification/qnli.py
- mindnlp/dataset/text_classification/qqp.py
- mindnlp/dataset/text_classification/rte.py
- mindnlp/dataset/text_classification/sogounews.py
- mindnlp/dataset/text_classification/sst2.py
- mindnlp/dataset/text_classification/stsb.py
- mindnlp/dataset/text_classification/wnli.py
- mindnlp/dataset/text_classification/yahooanswers.py
- mindnlp/dataset/text_classification/yelpreviewfull.py
- mindnlp/dataset/text_classification/yelpreviewpolarity.py
- mindnlp/dataset/text_generation/lcsts.py
- mindnlp/dataset/text_generation/penntreebank.py
- mindnlp/dataset/text_generation/wikitext103.py
- mindnlp/dataset/text_generation/wikitext2.py
Modify parameter type hints and code comments
> Modify parameter type hints and code comments

- mindnlp/dataset/machine_translation/iwslt2017.py
- mindnlp/dataset/machine_translation/multi30k.py
- mindnlp/dataset/process.py
- tests/ut/dataset/test_iwslt2017.py
- tests/ut/dataset/test_multi30k.py
> fix: Unify parameter names, values and positions

- mindnlp/abc/metric.py
- mindnlp/common/metrics.py
- mindnlp/engine/evaluator.py
- mindnlp/engine/metrics/__init__.py
- mindnlp/engine/metrics/accuracy.py
- mindnlp/engine/metrics/bleu.py
- mindnlp/engine/metrics/confusion_matrix.py
- mindnlp/engine/metrics/distinct.py
- mindnlp/engine/metrics/em_score.py
- mindnlp/engine/metrics/f1.py
- mindnlp/engine/metrics/m_c_c.py
- mindnlp/engine/metrics/pearson.py
- mindnlp/engine/metrics/perplexity.py
- mindnlp/engine/metrics/precision.py
- mindnlp/engine/metrics/recall.py
- mindnlp/engine/metrics/rouge.py
- mindnlp/engine/metrics/spearman.py
- tests/ut/common/test_metrics.py
- tests/ut/engine/test_evaluator.py
- tests/ut/engine/test_trainer.py
add metric classes Perplexity, RougeN, RougeL, Distinct, Precision, Recall, ConfusionMatrix, MCC, Pearson, Spearman, EmScore
> add metric classes

- mindnlp/utils/download.py
patch download parameter annotation
> patch download parameter annotation

- mindnlp/dataset/machine_translation/iwslt2016.py
- mindnlp/dataset/machine_translation/iwslt2017.py
- mindnlp/dataset/machine_translation/multi30k.py
- mindnlp/dataset/question_answer/squad1.py
- mindnlp/dataset/question_answer/squad2.py
- mindnlp/dataset/sequence_tagging/conll2000chunking.py
- mindnlp/dataset/sequence_tagging/udpos.py
- mindnlp/dataset/text_classification/agnews.py
- mindnlp/dataset/text_classification/amazonreviewfull.py
- mindnlp/dataset/text_classification/amazonreviewpolarity.py
- mindnlp/dataset/text_classification/cola.py
- mindnlp/dataset/text_classification/dbpedia.py
- mindnlp/dataset/text_classification/imdb.py
- mindnlp/dataset/text_classification/mnli.py
- mindnlp/dataset/text_classification/mrpc.py
- mindnlp/dataset/text_classification/qnli.py
- mindnlp/dataset/text_classification/qqp.py
- mindnlp/dataset/text_classification/rte.py
- mindnlp/dataset/text_classification/sogounews.py
- mindnlp/dataset/text_classification/sst2.py
- mindnlp/dataset/text_classification/stsb.py
- mindnlp/dataset/text_classification/wnli.py
- mindnlp/dataset/text_classification/yahooanswers.py
- mindnlp/dataset/text_classification/yelpreviewfull.py
- mindnlp/dataset/text_classification/yelpreviewpolarity.py
- mindnlp/dataset/text_generation/lcsts.py
- mindnlp/dataset/text_generation/penntreebank.py
- mindnlp/dataset/text_generation/wikitext103.py
- mindnlp/dataset/text_generation/wikitext2.py
> repair the annotation

- mindnlp/abc/modules/embedding.py
- mindnlp/modules/embeddings/fasttext_embedding.py
- mindnlp/modules/embeddings/glove_embedding.py
- mindnlp/modules/embeddings/word2vec_embedding.py
在load函数里添加了能用npy文件加载embedding的功能
> embedding load npy file

- mindnlp/engine/trainer.py
> trainer support loss_fn=None

- mindnlp/abc/modules/embedding.py
- mindnlp/dataset/text_classification/agnews.py
- mindnlp/modules/embeddings/fasttext_embedding.py
- mindnlp/modules/embeddings/glove_embedding.py
- mindnlp/modules/embeddings/word2vec_embedding.py
- tests/ut/dataset/test_agnews.py
> ag_news process fix

- examples/fasttext.py
- mindnlp/dataset/text_classification/agnews.py
fasttext模型的example，同时做了agnews对应的一点修改
> fasttext example

- mindnlp/dataset/sequence_tagging/__init__.py
- mindnlp/dataset/sequence_tagging/conll2000chunking.py
- mindnlp/dataset/utils.py
- tests/ut/dataset/test_conll2000chunking.py
> add conll2000chunking process

- examples/sequence_tagging.py
add BiLSTM-CRF sequence tagging model example
> add BiLSTM-CRF sequence tagging model example

- README.md
> readme: get started

- .github/workflows/make_wheel_releases.yml
add make_wheel_releases action
> add make_wheel_releases action

- mindnlp/models/__init__.py
- mindnlp/models/bert.py
- tests/ut/models/test_modeling_bert.py
add MindNLP Bert modeling 
函数式融合编程的BERT实现，对标huggingface
> 函数式融合编程的BERT实现，对标huggingface

- docs/locales/zh_CN/LC_MESSAGES/api.po
docs: add Chinese comments in loss
> docs: loss

- mindnlp/dataset/machine_translation/iwslt2016.py
- mindnlp/dataset/sequence_tagging/conll2000chunking.py
> fix iwslt2016 dataset and CoNLL2000Chunking_Process annotation

- mindnlp/modules/attentions.py
fix attention annotation 修复了attention模块注释的问题
> fix attention annotation

- docs/locales/zh_CN/LC_MESSAGES/api.po
docs: machine_translation,question_answer,text_generation
> docs: machine_translation,question_answer,text_generation

- docs/examples/sequence_tagging.rst
- docs/index.rst
> sequence_tagging example doc

- docs/locales/zh_CN/LC_MESSAGES/examples.po
sequence_tagging example chinese doc
> sequence_tagging example chinese doc

- docs/examples/sequence_tagging.rst
fix sequence_tagging example doc
> fix sequence_tagging example doc

- docs/examples/sequence_tagging.rst
- docs/locales/zh_CN/LC_MESSAGES/examples.po
update sequence_tagging chinese doc
> update sequence_tagging chinese doc

- docs/quick_start/dataset_and_transforms.rst
> docs: dataset and transforms (en)

- docs/locales/zh_CN/LC_MESSAGES/quick_start.po
> docs: dataset and transforms (zh_CN)

- docs/quick_start/modules.rst
> fix issue 282 quick_start/modules.rst

- docs/examples/machine_translation.rst
- docs/locales/zh_CN/LC_MESSAGES/api.po
- mindnlp/dataset/text_classification/rte.py
删除machine_translation中的jit参数
补充数据集部分文档翻译
> fix issue #289 and part of #276

- mindnlp/abc/backbones/pretrained.py
- mindnlp/models/t5/__init__.py
- mindnlp/models/t5/t5.py
- mindnlp/models/t5/t5_config.py
- tests/ut/models/t5/test_modeling_t5.py
T5Config, T5LayerNorm, T5DenseActDense, T5DenseGatedActDense, T5LayerFF, T5Attention, T5LayerSelfAttention, T5LayerCrossAttention, T5Block and ut of these blocks
> add blocks of T5 model

- .github/workflows/ci_pipeline.yaml
- mindnlp/abc/backbones/pretrained.py
- mindnlp/models/t5/t5.py
- tests/ut/models/t5/test_modeling_t5.py
T5Stack, T5Model, T5ForConditionalGeneration, T5EncoderModel
> add blocks of T5 model and uts

- docs/quick_start/use_callback.rst
> fix issue #283

- mindnlp/workflow/__init__.py
- mindnlp/workflow/downstream/__init__.py
- mindnlp/workflow/downstream/sentiment_analysis_model.py
- mindnlp/workflow/work.py
- mindnlp/workflow/workflow.py
- mindnlp/workflow/works/__init__.py
- mindnlp/workflow/works/sentiment_analysis.py
add sentiment analysis work and model in workflow
> add sentiment analysis work and model in workflow

- mindnlp/models/tinybert/tinybert.py
- mindnlp/models/tinybert/tinybert_config.py
- tests/ut/models/tinybert/test_tinybert.py
https://github.com/PurRigiN/mindnlp/blob/b80b4ebe5c0ae7d49a4b9552ee6387454929b7d2/tests/ut/models/tinybert/test_tinybert.py#L15
for
`tests/ut/models/tinybert/test_tinybert.py:27:0: R0904: Too many public methods (22/20) (too-many-public-methods)`
> Add TinyBert models

- examples/sentiment_analysis/bert_bd_public.ipynb
- mindnlp/workflow/work.py
- mindnlp/workflow/works/sentiment_analysis.py
add bert_senta_ipynb and _check_work_files content
> add bert_senta_ipynb and _check_work_files content

- mindnlp/models/erine/__init__.py
- mindnlp/models/erine/ernie.py
- mindnlp/models/erine/ernie_config.py
- tests/ut/models/ernie/test_ernie.py
> Add Ernie and UIE model

- mindnlp/models/erine/ernie.py
Fix ErnieModel attention_mask add tile operation
> Fix ErnieModel attention_mask add tile operation

- mindnlp/models/gpt2/config_gpt2.py
Reverts mindspore-lab/mindnlp#457
> Revert "updata gpt2_config"

- .readthedocs.yaml
> fix readthedocs sphinx build

- mindnlp/models/bloom/__init__.py
- mindnlp/models/bloom/bloom.py
- mindnlp/models/bloom/bloom_config.py
- mindnlp/models/longformer/longformer.py
- tests/ut/models/bloom/test_bloom_config.py
- tests/ut/models/bloom/test_modeling_bloom.py
- tests/ut/models/longformer/test_embeddings.py
1. bloom model
2. fp16 support
3. not support bf16
> add bloom model

- mindnlp/models/ernie/ernie_config.py
- mindnlp/transforms/tokenizers/__init__.py
- mindnlp/transforms/tokenizers/ernie_tokenizer.py
- tests/ut/transforms/test_ernie_tokenizer.py
Add ernie tokenizer (uie part)
> Add ernie tokenizer (uie part)

- mindnlp/models/bart/__init__.py
- mindnlp/models/bart/bart.py
- mindnlp/models/bart/bart_config.py
- tests/ut/models/bart/test_modeling_bart.py
> add bart model

- mindnlp/configs.py
- mindnlp/models/ernie/ernie.py
- mindnlp/models/ernie/ernie_config.py
- mindnlp/workflow/works/sentiment_analysis.py
- tests/ut/models/ernie/test_ernie.py
Fix ErnieConfig and ErniePretrainedModel for  UIE's "from_pretrained"
> Fix Ernie's config and model for "from_pretrained"

- mindnlp/engine/trainer/base.py
Trainer.run() set GRAPH_MODE  to avoid mindspore control flow issue.
> Trainer.run() set GRAPH_MODE to avoid mindspore control flow issue

- tests/ut/models/bert/test_modeling_bert.py
- tests/ut/models/bloom/test_bloom_config.py
- tests/ut/models/bloom/test_modeling_bloom.py
- tests/ut/models/clip/test_modeling_clip.py
- tests/ut/models/codegen/test_modeling_codegen.py
- tests/ut/models/cpm/test_modeling_cpm_ant.py
- tests/ut/models/ernie/test_ernie.py
- tests/ut/models/glm/test_modeling_glm.py
- tests/ut/models/gpt/test_modeling_gpt.py
- tests/ut/models/gpt2/test_modeling_gpt2.py
- tests/ut/models/gpt_neo/test_gpt_neo.py
- tests/ut/models/llama/test_modeling_llama.py
- tests/ut/models/llama/test_modeling_llama_hf.py
- tests/ut/models/longformer/test_embeddings.py
- tests/ut/models/luke/test_modeling_luke.py
- tests/ut/models/mobilebert/test_mobilebert.py
- tests/ut/models/nezha/test_modeling_nezha.py
- tests/ut/models/roberta/test_modeling_roberta.py
- tests/ut/models/rwkv/test_modeling_rwkv.py
- tests/ut/models/t5/test_modeling_t5.py
- tests/ut/models/tinybert/test_tinybert.py
- tests/ut/models/xlm/test_xlm.py
fix: remove .mindnlp in teardown
> fix: remove .mindnlp in teardown

- mindnlp/transforms/tokenizers/__init__.py
- mindnlp/transforms/tokenizers/ernie_tokenizer.py
- mindnlp/transforms/tokenizers/uie_tokenizer.py
- mindnlp/workflow/utils.py
- mindnlp/workflow/work.py
- mindnlp/workflow/workflow.py
- mindnlp/workflow/works/__init__.py
- mindnlp/workflow/works/information_extraction.py
- mindnlp/workflow/works/sentiment_analysis.py
Add information_extraction(UIEWork) to workflow & fix ernie_tokenizer
> Add information_extraction(UIEWork) to workflow & fix ernie_tokenizer

- mindnlp/dataset/question_answer/__init__.py
- mindnlp/dataset/question_answer/docvqa_zh.py
- tests/ut/dataset/test_hfdocvqa_zh.py
Add a url to download the dataset.
> Add docvqa_zh dataset

- mindnlp/dataset/hf_datasets/__init__.py
- mindnlp/dataset/hf_datasets/hf_duconv.py
- tests/ut/dataset/test_hfduconv.py
> add duconv

- .github/kaggle_gpu_test.py
Reverts mindspore-lab/mindnlp#617
> Revert "fix kaggle gpu test"

- mindnlp/dataset/machine_translation/multi30k.py
- requirements/requirements.txt
> fix multi30k url

- .github/workflows/ci_pipeline.yaml
- llm/peft/bert_mrpc_lora.py
- mindnlp/abc/__init__.py
- mindnlp/abc/configs/pretrained_config.py
- mindnlp/abc/container.py
- mindnlp/abc/models/pretrained_model.py
- mindnlp/models/bert/bert_config.py
- mindnlp/models/roberta/roberta_config.py
- mindnlp/peft/__init__.py
- mindnlp/peft/config.py
- mindnlp/peft/mapping.py
- mindnlp/peft/peft_model.py
- mindnlp/peft/tuners/lora.py
- mindnlp/peft/tuners/tuners_utils.py
- mindnlp/peft/utils/__init__.py
- mindnlp/peft/utils/other.py
- mindnlp/peft/utils/save_and_load.py
- mindnlp/transforms/tokenizers/roberta_tokenizer.py
> add PEFT:LORA support

- mindnlp/models/longt5/__init__.py
> first init for longt5

- mindnlp/transformers/configuration_utils.py
- mindnlp/transformers/models/gpt_bigcode/__init__.py
- mindnlp/transformers/models/gpt_bigcode/gpt_bigcode.py
- mindnlp/transformers/models/gpt_bigcode/gpt_bigcode_config.py
- mindnlp/transformers/models/gpt_bigcode/gpt_bigcode_tokenizer.py
+ `gpt_bigcode.py`                         # gpt_bigcode model
+ `gpt_bigcode_config.py`             # gpt_bigcode config
+ `gpt_bigcode_tokenizer.py`        # gpt_bigcode_tokenizer
using `trouble shooter` to check `bigcode/gpt_bigcode-santacoder` model
> finish gpt_bigcode's model, config and tokenizer

- llm/parallel/bert/bert_auto_parallel.py
- llm/parallel/bert/run_4_card.sh
- mindnlp/transformers/models/bert/modeling_graph_bert.py
use mindspore auto parallel.
> still need to change mindspore's source code to enable `model.build()` for `GPU`
> add auto parallel training for bert

- mindnlp/injection.py
- mindnlp/modules/functional/weight_norm.py
- mindnlp/transformers/modeling_utils.py
- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/tokenization_auto.py
- mindnlp/transformers/models/hubert/__init__.py
- mindnlp/transformers/models/hubert/configuration_hubert.py
- mindnlp/transformers/models/hubert/modeling_hubert.py
- mindnlp/transformers/models/wav2vec2/__init__.py
- mindnlp/transformers/models/wav2vec2/configuration_wav2vec2.py
- mindnlp/transformers/models/wav2vec2/feature_extraction_wav2vec2.py
- mindnlp/transformers/models/wav2vec2/modeling_wav2vec2.py
- mindnlp/transformers/models/wav2vec2/processing_wav2vec2.py
- mindnlp/transformers/models/wav2vec2/tokenization_wav2vec2.py
- mindnlp/utils/__init__.py
- mindnlp/utils/import_utils.py
- mindnlp/utils/testing_utils.py
- tests/ut/transformers/models/hubert/test_modeling_hubert.py
- tests/ut/transformers/models/wav2vec2/test_feature_extraction_wav2vec2.py
- tests/ut/transformers/models/wav2vec2/test_modeling_wav2vec2.py
- tests/ut/transformers/models/wav2vec2/test_processor_wav2vec2.py
- tests/ut/transformers/models/wav2vec2/test_tokenization_wav2vec2.py
Contents update:
- Hubert: model
- Wav2Vec: processor, feature_extractor, tokenizer
- weight_norm
- hijacks
- new: GroupNorm, Parameter inits
- fix: LayerNorm, Dense
The commit passed all following tests (on Windows):
```shell
SET RUN_SLOW=1
pytest -v -s tests/ut/transformers/models/hubert/test_modeling_hubert.py
pylint --rcfile=.github/pylint.conf mindnlp\injection.py
pylint --rcfile=.github/pylint.conf mindnlp\modules\functional\weight_norm.py
pylint --rcfile=.github/pylint.conf mindnlp\transformers\models\hubert
pylint --rcfile=.github/pylint.conf mindnlp\transformers\models\wav2vec2
pylint --rcfile=.github/pylint.conf tests\ut\transformers\models\hubert
pylint --rcfile=.github/pylint.conf tests\ut\transformers\models\wav2vec2
```
> add Hubert model

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/big_bird/__init__.py
- mindnlp/transformers/models/big_bird/big_bird/test_modeling_big_bird.py
- mindnlp/transformers/models/big_bird/configuration_big_bird.py
- mindnlp/transformers/models/big_bird/modeling_big_bird.py
- mindnlp/transformers/models/big_bird/tokenization_big_bird.py
- mindnlp/transformers/models/big_bird/tokenization_big_bird_fast.py
- tests/ut/transformers/models/big_bird/test_modeling_big_bird.py
It has an ut failure because of precision.
> big_bird has a ut failure

- examples/classification/dual_bert_imdb_scratch.ipynb
- mindnlp/transformers/models/bert/modeling_bert.py
Added an implementation of the Bert model using dual operators, as well as an example of training it from scratch on IMDB dataset.
> Added dual-valued Bert model and example of using it

- mindnlp/transformers/models/table_transformer/__init__.py
From gitee issue: https://gitee.com/mindspore/community/issues/I835ND
> Add table_transformer model

- examples/tensor_decomposition/dual_bert_td.ipynb
- mindnlp/_legacy/hypercomplex/tensor_decomposition/hypercomplex_td.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/algorithm/dual_svd.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/algorithm/qr.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/algorithm/star_svd.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/algorithm/svd.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/algorithm/t_svd.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/complex/_complex_algebra_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/complex/complex_algebra_factory.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/dual/_dual_algebra_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/dual/dual_algebra_factory.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/_hc_math_obj_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/_hc_matrix_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/_hc_scalar_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/_hc_vector_impl.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/hc_algebra_factory.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/hc_matrix.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/hc_scalar.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/hypercomplex/hc_vector.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/matrix.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/real/real_matrix.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/real/real_scalar.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/real/real_vector.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/scalar.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/scalar_visitor.py
- mindnlp/_legacy/hypercomplex/tensor_decomposition/linal/basics/vector.py
Added hypercomplex Tensor decomposition and example of using it for dual-valued Bert model
> Added hypercomplex Tensor Decomposition and example of using it

- llm/finetune/t5/README.md
- llm/finetune/t5/t5_fintune.py
- llm/finetune/t5/util_t5ft.py
> t5_finetune

- docs/en/api/engine/callbacks.md
- docs/en/api/engine/export.md
- docs/en/api/engine/index.md
- docs/en/api/engine/train_args/base.md
- docs/en/api/engine/train_args/seq2seq.md
- docs/en/api/engine/trainer/base.md
- docs/en/api/engine/trainer/default_func.md
- docs/en/api/engine/utils.md
- mkdocs.yml
补齐Engine文档
issue链接：
https://gitee.com/mindspore/community/issues/I9GVKW
> Engine documentation completion

- mindnlp/engine/callbacks.py
- mindnlp/engine/train_args/base.py
- mindnlp/engine/trainer/base.py
- mindnlp/engine/utils.py
engine文档修改，更换了带有torch nn.module这些的内容
任务链接：https://gitee.com/mindspore/community/issues/I9GVKW
> engine doc

- llm/peft/loha/train_bert_loha/peft_loha_seq_cls.ipynb
- mindnlp/peft/tuners/loha/config.py
- mindnlp/peft/utils/save_and_load.py
> Fix bugs in loha and add example for it

- docs/en/api/dataset/BaseMapFunction.md
- docs/en/api/dataset/index.md
- docs/en/api/dataset/load_dataset.md
- docs/en/api/dataset/transforms.md
- mkdocs.yml
> Create dataset module documentation

- llm/inference/generate_comments/generate_comments.py
> Auto generate comments code

- mindnlp/peft/__init__.py
- mindnlp/peft/mapping.py
- mindnlp/peft/peft_model.py
- mindnlp/peft/tuners/__init__.py
- mindnlp/peft/tuners/poly/__init__.py
- mindnlp/peft/tuners/poly/config.py
- mindnlp/peft/tuners/poly/layer.py
- mindnlp/peft/tuners/poly/model.py
- mindnlp/peft/tuners/poly/router.py
- mindnlp/peft/utils/save_and_load.py
```Python
r = 8  # rank of lora in poly
n_tasks = 4  # number of tasks
n_skills = 2  # number of skills (loras)
n_splits = 4  # number of heads
```
mindnlp/print_trainable_parameters
peft/print_trainable_parameters
> Basic support for Poly

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/squeezebert/__init__.py
- mindnlp/transformers/models/squeezebert/configuration_squeezebert.py
- mindnlp/transformers/models/squeezebert/modeling_squeezebert.py
- mindnlp/transformers/models/squeezebert/tokenization_squeezebert.py
- mindnlp/transformers/models/squeezebert/tokenization_squeezebert_fast.py
- tests/ut/transformers/models/squeezebert/test_modeling_squeezebert.py
> 【昇腾AI创新大赛】 squeezebert

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/roc_bert/__init__.py
- mindnlp/transformers/models/roc_bert/configuration_roc_bert.py
- mindnlp/transformers/models/roc_bert/modeling_roc_bert.py
- mindnlp/transformers/models/roc_bert/tokenization_roc_bert.py
- tests/ut/transformers/models/roc_bert/test_modeling_roc_bert.py
> 【昇腾AI创新大赛】roc_bert

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/mvp/__init__.py
- mindnlp/transformers/models/mvp/configuration_mvp.py
- mindnlp/transformers/models/mvp/modeling_mvp.py
- mindnlp/transformers/models/mvp/tokenization_mvp.py
- mindnlp/transformers/models/mvp/tokenization_mvp_fast.py
- tests/ut/transformers/models/mvp/test_modeling_mvp.py
> 【昇腾AI创新大赛】mvp

- mindnlp/sentence/SentenceTransformer.py
- mindnlp/sentence/models/Pooling.py
- mindnlp/sentence/models/Transformer.py
- mindnlp/sentence/models/__init__.py
- mindnlp/sentence/util.py
增加了sentence transformer模块，支持模型加载和encode
> add sentence transformer module

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/switch_transformers/__init__.py
- mindnlp/transformers/models/switch_transformers/configuration_switch_transformers.py
- mindnlp/transformers/models/switch_transformers/modeling_switch_transformers.py
- tests/ut/transformers/models/switch_transformers/test_modeling_switch_transformers.py
> 【昇腾AI创新大赛】switch_transformers

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/wavlm/__init__.py
- mindnlp/transformers/models/wavlm/configuration_wavlm.py
- mindnlp/transformers/models/wavlm/modeling_wavlm.py
- tests/ut/transformers/models/wavlm/test_modeling_wavlm.py
> 【昇腾AI创新大赛】wavlm

- llm/peft/lora/train_gpt_neox/gpt_neox_lora.ipynb
- llm/peft/lora/train_gpt_neox/gpt_neox_lora.py
- mindnlp/engine/trainer/base.py
- mindnlp/engine/utils.py
- mindnlp/transformers/integrations/peft.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/gpt_neox/modeling_gpt_neox.py
- mindnlp/transformers/models/gpt_neox_japanese/modeling_gpt_neox_japanese.py
Updated GPT_NeoX sample code for instruction fine-tuning based on LoRa.
> Updated GPT_NeoX sample code for instruction fine-tuning based on LoRa.

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/owlv2/__init__.py
- mindnlp/transformers/models/owlv2/configuration_owlv2.py
- mindnlp/transformers/models/owlv2/image_processing_owlv2.py
- mindnlp/transformers/models/owlv2/modeling_owlv2.py
- mindnlp/transformers/models/owlv2/processing_owlv2.py
- tests/ut/transformers/models/owlv2/test_image_processor_owlv2.py
- tests/ut/transformers/models/owlv2/test_modeling_owlv2.py
Reverts mindspore-lab/mindnlp#1287
> 还原【昇腾AI创新大赛】add owlv2 model

- mindnlp/transformers/models/whisper/README.MD
- mindnlp/transformers/models/whisper/modeling_graph_whisper.py
support for whisper graph mod
can quickly started with the README.MD
> support for Whisper graph mode

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/mctct/__init__.py
- mindnlp/transformers/models/mctct/configuration_mctct.py
- mindnlp/transformers/models/mctct/feature_extraction_mctct.py
- mindnlp/transformers/models/mctct/modeling_mctct.py
- mindnlp/transformers/models/mctct/processing_mctct.py
- tests/ut/transformers/models/mctct/test_feature_extraction_mctct.py
- tests/ut/transformers/models/mctct/test_modeling_mctct.py
- tests/ut/transformers/models/mctct/test_processor_mctct.py
> 【社区实习】add M-CTC-T model

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/image_processing_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/bit/modeling_bit.py
- mindnlp/transformers/models/vit_hybrid/__init__.py
- mindnlp/transformers/models/vit_hybrid/configuration_vit_hybrid.py
- mindnlp/transformers/models/vit_hybrid/image_processing_vit_hybrid.py
- mindnlp/transformers/models/vit_hybrid/modeling_vit_hybrid.py
- tests/ut/transformers/models/vit_hybrid/test_modeling_vit_hybrid.py
对**modeling_bit.py**文件的修改主要是将有一处con2v的pad_mode参数从"same"改为"valid"
`pad_mode='pad' if padding != 0 else 'valid',`
经验证，当padding为0时，pad_mode应该为'valid'，'same'应该是pytorch的写法，应该是原作者疏漏了没改
还有就是vscode自动将行首的空格给删掉了。
> 【社区实习】add Vit hybrid model

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/auto/tokenization_auto.py
- mindnlp/transformers/models/xmod/__init__.py
- mindnlp/transformers/models/xmod/configuration_xmod.py
- mindnlp/transformers/models/xmod/modeling_xmod.py
- tests/ut/transformers/models/xmod/test_modeling_xmod.py
> 【社区实习】Xmod

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/dinov2/__init__.py
- mindnlp/transformers/models/dinov2/configuration_dinov2.py
- mindnlp/transformers/models/dinov2/modeling_dinov2.py
- mindnlp/transformers/models/vit_hybrid/modeling_vit_hybrid.py
- tests/ut/transformers/models/dinov2/test_modeling_dinov2.py
社区实习任务：https://gitee.com/mindspore/community/issues/I9UUPK
> 【社区实习】DINOv2

- mindnlp/core/nn/functional.py
- mindnlp/transformers/activations.py
- mindnlp/transformers/modeling_utils.py
Reverts mindspore-lab/mindnlp#1429
> Revert "fix albert ut"

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/auto/configuration_auto.py
- mindnlp/transformers/models/prophetnet/__init__.py
- mindnlp/transformers/models/prophetnet/configuration_prophetnet.py
- mindnlp/transformers/models/prophetnet/modeling_prophetnet.py
- mindnlp/transformers/models/prophetnet/tokenization_prophetnet.py
- mindnlp/transformers/models/tapex/__init__.py
- mindnlp/transformers/models/tapex/tokenization_tapex.py
- tests/ut/transformers/models/prophetnet/test_modeling_prophetnet.py
- tests/ut/transformers/models/tapex/test_tokenization_tapex.py
Prophetnet and tapex 模型迁移 
Tapex任务链接：https://gitee.com/mindspore/community/issues/I9V044
Prophetnet任务链接：https://gitee.com/mindspore/community/issues/I9UYTF
> Prophetnet and tapex 模型迁移

- mindnlp/transformers/models/__init__.py
- mindnlp/transformers/models/roberta_prelayernorm/__init__.py
- mindnlp/transformers/models/roberta_prelayernorm/configuration_roberta_prelayernorm.py
- mindnlp/transformers/models/roberta_prelayernorm/modeling_roberta_prelayernorm.py
- tests/ut/transformers/models/roberta_prelayernorm/test_modeling_roberta_prelayernorm.py
add model roberta_prelayernorm
> add model roberta_prelayernorm

- llm/mindpilot/README.md
MindPilot V0.0.1 初步开发完成
仓库地址：https://github.com/ResDream/MindPilot
> add: MindPilot README.md

- mindnlp/utils/testing_utils.py
> chore: update testing_utils.py

- applications/VideoMAE/Quick_inference_with_VideoMAE.ipynb
- mindspore推理结果：
- pytorch推理结果：
> 【开源实习】VideoMAE模型应用开发

- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/bge_m3/modeling_bge_m3.py
注册BgeM3Model
&运算符不支持bool
mindspore.ops.unique与mindnlp.core.unique返回值不同
> fix: fix BgeM3Model

- README.md
Added a table of contents in the doc for better navigation
> add toc in readme.md

- mindnlp/transformers/models/auto/modeling_auto.py
- mindnlp/transformers/models/deepseek_v2/modeling_deepseek.py
本地测试使用mindspore 2.2.14可以正常输出结果，用2.4会有问题；MoE部分缺少封装，等封装完毕后会跟进维护
> 重做deepseek_v2模型并补注册

- mindnlp/core/ops/random.py
expose prob as positional argument for bernoulli ops
> expose prob as positional argument for bernoulli ops

- llm/inference/janus_pro/understanding.py
- mindnlp/core/ops/array.py
- mindnlp/transformers/cache_utils.py
cast to fp16 and change file path
> cast to fp16 and change file path

- docs/en/tutorials/quick_start.md
> Fix incorrect import quick_start.md

- llm/finetune/Align/eval_model.py
- llm/finetune/Align/finetune.py
实现了ALIGN模型在MSCOCO val2017数据集上的微调实验。  
任务链接在(https://gitee.com/mindspore/community/issues/IAUOS5)。  
数据集为MSCOCO val2017，模型为kakaobrain/align，硬件环境晟腾910b  
MindSpore实现的代码基于MindNLP。  
PyTorch的基准实验基于transformers框架，使用4060硬件，仓库位于[(https://github.com/huadaox/kakaobrain_align_ft)]。  
实验结果如下：
> 【开源实习】align模型微调 IAUOS5

- mindnlp/peft/peft_model.py
- mindnlp/peft/utils/save_and_load.py
- mindnlp/transformers/models/qwen2/modeling_qwen2.py
> PeftModel supports saving and loading safetensors

- mindnlp/core/nn/modules/conv.py
This PR adapts the `Conv1d` module to support both the new and legacy MindSpore interfaces.
It implements a fallback mechanism that checks the availability of new operations (`conv1d_ext_op`, `conv1d_padding_op`, and `pad_ext`) and uses them when available. If not, the implementation gracefully falls back to the legacy approach by simulating `Conv1d` using `Conv2D`.
Hard Environment:
Ascend（snt9b|32G）
Software Environment / 软件环境 (Mandatory / 必填):
-- MindSpore version (e.g., 20250414 master) : 2.6.0 & 2.5.0（conda env - mindnlp）
-- Python version (e.g., Python 3.7.5) : 3.10.0 （conda env - mindnlp）
-- CANN Tookies version : 8.1.RC1.alpha002
-- OS platform and distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.4 LTS
-- GCC/Compiler version (if compiled from source): 11.04
-- Docker image : …
> [Fix] Adapt Conv1d to support both new and legacy MindSpore interfaces

- applications/ConvNeXt/ConvNeXt.ipynb
https://gitee.com/mindspore/community/issues/IAADCA
> 【开源实习】ConvNeXT模型应用开发
